version: "3"
services:
  publisher-service-1:
    build:
      context: ./publisher_service/.
      dockerfile: ./Dockerfile
    container_name: publisher_service_1_app
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: message_queue
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always