version: "3"
services:
  publisher-service-1:
    build:
      context: .
      dockerfile: ./publisher-service-1/Dockerfile
    container_name: publisher_service_1_app
    depends_on:
      - rabbitmq
  consumer-service-2:
    build:
      context: .
      dockerfile: ./consumer_service_2/Dockerfile
    container_name: consumer_service_2_app
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: message_queue
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always