version: "3"
services:
  consumer_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MSG_QUEUE_CONN_STRING=amqp://guest:guest@rabbitmq:5672
      - MSG_QUEUE_NAME=tech_task
      - MSG_QUEUE_EXCHANGE_KIND=topic
      - MSG_QUEUE_EXCHANGE_NAME=events
      - MSG_QUEUE_ROUTE_KEY=info
      - READ_BUFFER_SIZE=1024
      - WRITE_BUFFER_SIZE=1024
      - MSG_QUEUE_CHECK_ORIGIN=true
      - MSG_QUEUE_USERNAME=guest
      - MSG_QUEUE_PASSWORD=guest
    container_name: consumer_service
    ports:
      - "8208:8208"
    depends_on:
      - rabbitmq
  rabbitmq:
    container_name: message_queue
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    restart: always